version: '3.6'

services:

  unbscholar.dspace.lib.unb.ca:
    build:
      context: .
    restart: always
    container_name: unbscholar.dspace.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    ports:
      - "3507:8080"
    networks:
      - unbscholar.dspace.lib.unb.ca

  unbscholar.postgres.lib.unb.ca:
    build:
      context: postgres/
    restart: always
    env_file:
      - ./env/dspace.env
    expose:
      - "5432"
    networks:
      - unbscholar.dspace.lib.unb.ca

networks:
  unbscholar.dspace.lib.unb.ca:
    name: unbscholar.dspace.lib.unb.ca
